# Generated by Django 5.0.3 on 2024-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commander",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Commander name"),
                ),
                ("year", models.IntegerField(verbose_name="Commander year")),
                ("did", models.CharField(max_length=255, verbose_name="Commander did")),
                (
                    "area",
                    models.CharField(max_length=255, verbose_name="Commander area"),
                ),
            ],
            options={
                "verbose_name": "Commander list",
                "db_table": "commander",
                "ordering": ("id",),
            },
        ),
    ]
