# Generated by Django 5.0.3 on 2024-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_comanders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commander",
            name="image",
            field=models.ImageField(
                default="image/comander.jpeg",
                upload_to="image",
                verbose_name="commander image",
            ),
        ),
    ]
